import React, { useState } from 'react';

/**
 * OptimizedImage Component
 *
 * Features:
 * - Tries WebP version first (from /home/optimized/), falls back to original PNG
 * - Lazy loading by default (eager for priority images)
 * - Async decoding to prevent main thread blocking
 * - Native CSS fade-in on load (no framer-motion overhead per image)
 */
const OptimizedImage = ({
  src,
  alt,
  className,
  width,
  height,
  priority = false,
  style,
  ...props
}) => {
  const [useFallback, setUseFallback] = useState(false);

  // Attempt the WebP version first (generated by scripts/optimize-images.mjs)
  const getOptimizedSrc = (originalSrc) => {
    if (originalSrc && originalSrc.startsWith('/home/') && !originalSrc.includes('/optimized/')) {
      const fileName = originalSrc.split('/').pop().replace(/\.(png|jpg|jpeg)$/i, '.webp');
      return `/home/optimized/${fileName}`;
    }
    return originalSrc;
  };

  const optimizedSrc = getOptimizedSrc(src);
  const finalSrc = useFallback ? src : optimizedSrc;

  return (
    <img
      src={finalSrc}
      alt={alt || ''}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      decoding="async"
      onError={() => {
        if (!useFallback) setUseFallback(true);
      }}
      className={className}
      style={style}
      {...props}
    />
  );
};

export default OptimizedImage;
